# create plots for Justine

#####################################################################################################################################
################################## REGRESSION ANALYSIS OF BEETLE ABUNDANCE RESPONSES TO FOREST COVER ################################
#####################################################################################################################################

# GLMM: N ~ FC | Landscape

# USES BEETLE ABUNDANCES SUMMED AT THE POINT LEVEL
# USES FC FROM 200m BUFFERS AROUND POINTS

# set working directory
setwd("/Users/Tyler/Dropbox/Interface/Dados/Non-Geospatial/Winners_Losers_Traits/Analysis/Data")

# load base beetle dataframe
b.df <- readRDS ( "b.df.rds" )

head(b.df)

# load libraries
library(xlsx)
library(reshape)
library(plyr)
library(reshape2)
library(dplyr)
library (rgdal)
library (rgeos)
library (spdep)
library (plyr)
library(ggplot2)
library (caper)
library (ape)
library (MuMIn)
library (lme4)


################################## MANIPULATE DATA FOR THIS PARTICULAR APPROACH ################################## 

# create df with unique entry for each beetle species and associated attributes
b.sp.df <- ddply ( b.df, .(Species , Diel , Nest , Biogeo , BM , Hab , Diet, N.tot), summarize, mean(N.tot))

# subset relevant columns
b.sp.df <- b.sp.df[,1:8]

# b.sp.df<- data.frame(unique(b.df$Species))
# colnames(b.sp.df) <- ("Species")

### change perFC column in b.df to contain 200m buffer FC levels

# import 200m buffer FC data
fc.pt.200m.df <- read.csv("Landscape_composition_pitfalls.csv", header = T)

# subset for 200m buffer
fc.pt.200m.df <- subset (fc.pt.200m.df, fc.pt.200m.df$Buffer_m == 200)

# subset for forest cover
fc.pt.200m.df <- subset (fc.pt.200m.df, fc.pt.200m.df$Class == 'forest')

# collapse traps to point level, averaging trap buffer FC values
fc.pt.200m.df <- ddply (fc.pt.200m.df, .(Landscape, Point, Code_min), 
                        summarize, perFC = mean(Per_area))

# rectify column names
colnames(fc.pt.200m.df) <- c( "Landscape", "Point" , "TrapID" , "pt.200m.perFC" )

# subset for only TrapID and 200m FC cols
fc.pt.200m.df <- subset (fc.pt.200m.df, select = c( "TrapID", "pt.200m.perFC" ))

# merge 200m pt buffer FC data with b.df
b.df <- merge(b.df, fc.pt.200m.df, by = "TrapID")


################################################ Plot N ~ FC for all each beetle species

b.sp.df_subset <- subset (b.sp.df, (b.sp.df$Species %in% c("Dichotomius.mormon" , "Dichotomius.quadrinodosus")))

for (i in b.sp.df_subset$Species) {
  
  # create df with entries as all captures of a particular species
  b.par.df <- subset (b.df , b.df$Species == i) # omitting/including zeros doesn't seem to affect model
  
  # plot N ~ FC for particular species
  plot(b.par.df$pt.200m.perFC, jitter(b.par.df$N, 0.4), main = i, xlab = "Percent Forest Cover (200m Point Buffer)", 
       ylab = "Point-Level Abundance (N)")
  
  print (i)
  
}

################################################ CALCULATE N ~ FC RESPONSES FOR ALL BEETLE SPECIES

# create blank beetle FC response df
b.respFC.df <- data.frame(
  Species = factor(), 
  Intercept = double(),
  Inter.error = double(),
  Inter.t.val = double(),
  Inter.p.val = double(), 
  Slope = double(),
  Slope.error = double (),
  Slope.t.val = double(),
  Slope.p.val = double()
) 
# set levels of species var
levels(b.respFC.df$Species) <- unique (b.sp.df$Species)

# initialize row 1 as first slot of b.respFC.df to be filled
row = 1

# iterate response calculation over all beetle species and store in b.respFC.df
for (i in b.sp.df$Species) {
  
  # create df with entries as all captures of a particular species
  b.par.df <- subset (b.df , b.df$Species == i) # do we omit zeros?
  
  # plot N ~ FC for particular species
  b.lm.par <- glmer (b.par.df$N ~ b.par.df$pt.200m.perFC + (1|b.par.df$Landscape), family = poisson)
  
  print (summary (b.lm.par)$coefficients)
  
  b.respFC.df[row, 1] <- (i)
  b.respFC.df[row,2:5] <- summary (b.lm.par)$coefficients[1,]
  b.respFC.df[row,6:9] <- summary (b.lm.par)$coefficients[2,]
  
  row <- row + 1
}

b.respFC.df$Slope.p.val <- round(b.respFC.df$Slope.p.val, 3)

print (b.respFC.df)
summary (b.respFC.df)

hist (b.respFC.df$Slope, breaks = 20)

# species with significant slope coefficients
b.sigResp <- subset (b.respFC.df, b.respFC.df$Slope.p.val < 0.05)

hist (b.sigResp$Slope, breaks = 15)
hist (b.sigResp$Slope.p.val, breaks = 15)


### Export summary of betas generated by this modeling approach

# subset b.respFC.df for slopes and p-values
b.respFC.df_betas <- subset(b.respFC.df, select = c("Species", "Slope", "Slope.p.val"))

# rename columns to specify modeling approach number
colnames(b.respFC.df_betas) = c("Species", "b_glmm_200_Slope", "b_glmm_200_p.val")

#  save as RDS object
saveRDS(b.respFC.df_betas, "b_glmm_200.df")





################################################ MERGE N ~ FC RESPONSES WITH b.sp.df

b.sp.df <- merge(b.respFC.df, b.sp.df)

head(b.sp.df)

# make row names of b.sp.df into species names
rownames(b.sp.df) <- b.sp.df$Species


################################################ MODEL RESPONSES ~ TRAITS | PHYLO

#### Import phylo tree object from Kelley here
b.tre <- read.tree("b.sp.tre")
b.tre$node.label <- NULL

# generate comparative phylogenetic autocorrelation object
b.comp <- comparative.data(b.tre, b.sp.df, Species, vcv=TRUE)

# build pgls model
glmm_200.pgls <- pgls(Slope ~ BM + Diet + Diel + Nest, b.comp)

# + Hab  --- generates error
# + Biogeo ---generates error


# generate all possible models and rank by AIC

pgls_200_mods.table <- dredge(glmm_200.pgls, beta = c("none", "sd", "partial.sd"), evaluate = TRUE,
                              rank = "AICc", fixed = NULL)

print (pgls_200_mods.table)

