install.packages ("PBSmapping")
install.packages ("sp") 
install.packages ("rgdal") 
install.packages ("raster")
install.packages ("rgeos") 
install.packages ("maptools")
install.packages ("xlsx")
install.packages ("reshape")
install.packages ("plyr")
install.packages ("reshape2")
install.packages ("dplyr")
install.packages ("raster")
install.packages ("GISTools")
install.packages ("gpclib")
install.packages ("rgdal")
install.packages ("spdep")
install.packages ("ggplot2")
install.packages("caper")
install.packages("readxl")
install.packages("mice")
install.packages("rtf")
install.packages("DataCombine")
install.packages("R2admb")
install.packages("glmmADMB")
install.packages("MuMIn")
install.packages("FD")
install.packages("nlme")
install.packages("picante")
install.packages("stringr")
install.packages("MASS")
install.packages("lme4")
install.packages("coda")
install.packages("reshape")
require("lattice")
install.packages("plotrix")
install.packages("dataframes2xls")
install.packages("gdata")
install.packages("vegan")
install.packages("fields")
install.packages("Matrix")  
install.packages("abind")  
install.packages("doBy")
install.packages("gdistance")
install.packages("sp")
install.packages("xlsx")
install.packages("reshape2")
install.packages("languageR") 
install.packages("car")  
install.packages("ape")  
install.packages("geiger")
install.packages("phytools")
install.packages("ade4")
install.packages("betareg")
install.packages("stats")
install.packages("lmerTest")
install.packages("perm")
install.packages("graphics")
install.packages("plotrix")
install.packages("MASS")  
install.packages("arm")  
install.packages("xtable")  
install.packages("fields")
install.packages("Hmisc") 
install.packages("abind")  
install.packages("gtools")
install.packages("gmodels") 
install.packages("geiger")
install.packages("phangorn")
install.packages("gridExtra")
install.packages("gridGraphics")
install.packages("ggplot2")
install.packages("plyr")

library(caper)
library(mice)
library(rtf)
library(DataCombine)
library(R2admb)
library(glmmADMB)
library(MuMIn)
library(FD)
library(nlme)
library(picante)
library(stringr)
library(MASS)
library(lme4)
library(coda)
library(reshape)
require(lattice)
library(plotrix)
library(dataframes2xls)
library(gdata)
library(vegan)
library(fields)
library(Matrix)  
library(abind)  
library(doBy)
library(gdistance)
library(sp)
library(xlsx)
library(reshape2)
library(languageR) 
library(car)  
library(ape)  
library(geiger)
library(phytools)
library(ade4)
library(betareg)
library(stats)
library(lmerTest)
library(perm)
library(graphics)
library(plotrix)
library(MASS)  
library(arm)  
library(xtable)  
library(fields)
library(Hmisc) 
library(abind)  
library(gtools)
library(gmodels) 
library(geiger)
library(phangorn)
library(gridExtra)
library(gridGraphics)
library(ggplot2)
library(plyr)
library(readxl)


